### PR TITLE
Make 1.20.1 fabric runnable (With Tabs)

### PR DESCRIPTION
**Pull request by marlester-dev**

### CODE REVIEW

**Comment by marlester-dev** [comment]
@Tamaized

**Comment by Tamaized** [comment]
How does this currently compare to the released 1.20.1 version for Forge?

**Comment by marlester-dev** [comment]
> How does this currently compare to the released 1.20.1 version for Forge?

I think there are no magic paintings in this version

**Comment by IAFEnvoy** [comment]
Firstly, as the tf team said, due to assets copyright, republish fork is not allowed.

Then, you use my code without my permission. Although this project allow fork, you need to ask me and the whole tf team anyway.

**Comment by Tamaized** [comment]
What republish are you talking about?

**Pull request closed without merging**
