### PR TITLE
Make 1.20.1 fabric runable

### PR DESCRIPTION
**Pull request by IAFEnvoy**
I have ported almost everything and it can run now. But there are still a lot of bugs to be fixed. I will fix them later.

### CODE REVIEW

**Comment by tiredtires** [comment]
Now this is huge

**Comment by TheEscaper** [comment]
Please dude. Looks like You are our only hope

**Review by Tamaized — CHANGES_REQUESTED** [review]
Unless pulled from upstream, do not change formatting styles.

A lot of indentations in many files are being changed in this PR.

**Comment by IAFEnvoy** [comment]
anyway can you provide a configure file for idea so that i can format code with correct configuration

**Pull request closed without merging**
